package com.cz.seckill.seckill.mapper;

import com.cz.seckill.seckill.database.model.MmallOrder;
import java.util.List;

public interface MmallOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order
     *
     * @mbggenerated
     */
    int insert(MmallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order
     *
     * @mbggenerated
     */
    MmallOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order
     *
     * @mbggenerated
     */
    List<MmallOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MmallOrder record);
}